spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myorder?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sa123456

  jpa:
    show-sql: true

server:
    context-path: /sell
